### ISSUE TITLE
firmware compatibility

### ISSUE THREAD

**Issue by benasse** [jonbulica99/yealink-remote-manager#1]
What is the firmware version on your phones?
I try to reboot a T46G without success.

**Comment by jonbulica99** [comment]
My phone is running on firmware `2.73.0.50`. Do the other commands work for you?

**Comment by benasse** [comment]
I use the `51.80.0.75` unfortunately not.

The url has changed but should be backwards compatible according to the documentation.

I did not manage to restart the phone even with the new url: `http://<phone_ip>/servlet?Key=Reboot`

**Comment by jonbulica99** [comment]
Then it probably isn't supported. I'd contact the manufacturer for further support.
